name: Push Procution

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: heldernf/portfolio

      - name: Push da public(pasta de produção) para o repositório privado(produção)
        run: |
          cd $GITHUB_WORKSPACE/public
          git init
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Push da pasta de produção para o repositório privado"
          git push https://github.com/heldernf/portfolio-priv main