name: Push Folder to Another Repository
on:
  push:
    branches:
      - main

jobs:
  copy-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.SSH_PORTFOLIO_PROD }} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Push to Repo Production
        run: |
          cd public
          git config --global init.defaultBranch main
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git init
          git add .
          git commit -m "Push to Production" -q
          git push --force git@github.com:heldernf/portfolio-priv.git main