name: Push Folder to Another Repository
on:
  push:
    branches:
      - main

jobs:
  copy-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push to Repo Production
        run: |
          cd public
          git config --global init.defaultBranch main
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git init
          git remote origin git@github.com:heldernf/portfolio-priv.git
          git add .
          git commit -m "Push to Production" -q
          git push --force origin main