name: Push Procution

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{secrets.SSH_KEY}}

      - name: Push to production
        run: |
          git remote add production git@github.com:heldernf/tst.git
          git init
          git config --global user.email "github@noreplay.com"
          git config --global user.name "GitHub Actions"
          git pull
          git push production main