name: Push Procution

on:
  push:
    branches:
      - main

jobs:
  push_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}

      - name: Configurar Git remoto
        run: |
          git remote add production ${{secrets.SSH_KEY}}:heldernf/portfolio-priv.git

      - name: Fazer push para o repositório de production
        run: git push production main