name: Push Procution

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: heldernf/portfolio
          ref: main
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Automatically created pull request"
          title: "Automatically created pull request"
          body: "This pull request was automatically created by GitHub Actions."
          branch: main
          base: main
          repository: heldernf/portfolio-priv