name: Push Procution

on:
  push:
    branches:
      [main]

jobs:
  push_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          fetch-depth: 0

      - name: Configurar Git remoto
        run: |
          git remote add production git@github.com:heldernf/portfolio-priv.git

      - name: Fazer push para o repositório de production
        run: git push production main