name: Push Folder to Another Repository
on:
  push:
    branches:
      - main

jobs:
  copy-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout priv
        uses: actions/checkout@v4
        with:
          repository: heldernf/portfolio-priv
          ssh-key: ${{ secrets.SSH_KEY }}
          path: portfolio-priv

      - name: Push to Repo Production
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git push --force git@github.com:heldernf/portfolio-priv.git main