name: Push Procution

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: heldernf/portfolio
          ref: main

      - name: Push da public(pasta de produção) para o repositório privado(produção)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --prune
          git reset --hard origin/main
          git remote remove origin
          git remote add origin https://github.com/heldernf/tst.git
          git push origin main