name: Push Procution

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Push to production
        run: |
          git clone https://github.com/heldernf/portfolio
          git remote add production git@github.com:heldernf/portfolio-priv.git
          git pull
          git push production main