name: Push Procution

on:
  push:
    branches:
      [main]

jobs:
  push_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Git remoto
        run: |
          git remote add production https://github.com/heldernf/portfolio-priv

      - name: Fazer push para o repositório de production
        run: git push production main