name: Push Procution

on:
  push:
    branches:
      [main]

jobs:
  push_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Git remoto
        run: |
          git remote add B https://github.com/heldernf/tst.git

      - name: Fazer push para o repositório B
        run: git push B main