name: Push Procution

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{secrets.SSH_KEY}}

      - name: Configurar Git remoto
        run: |
          git remote add production git@github.com:heldernf/portfolio-priv.git
          git pull

      - name: Fazer push para o repositório de production
        run: git push production main