name: Deploy to production
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependences
        run: |
          cd public
          composer install

      - name: Run a command with interactive prompt
        run: |
          expect -c '
            spawn ${{ secrets.SSH_LOGIN_COMMAND }}
            expect ${{ secrets.SSH_LOGIN_COMMAND }}"'s password: "
            send ${{ secrets.SSH_LOGIN_PASSWORD }}\r
            interact
          '

      - name: Deploy to hostinger
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: "./public/*"
          TARGET: ${{ secrets.REMOTE_TARGET }}